// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc/grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Byzantium_GetMessage_FullMethodName  = "/Byzantium/GetMessage"
	Byzantium_SendMessage_FullMethodName = "/Byzantium/SendMessage"
)

// ByzantiumClient is the client API for Byzantium service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ByzantiumClient interface {
	GetMessage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error)
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type byzantiumClient struct {
	cc grpc.ClientConnInterface
}

func NewByzantiumClient(cc grpc.ClientConnInterface) ByzantiumClient {
	return &byzantiumClient{cc}
}

func (c *byzantiumClient) GetMessage(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, Byzantium_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byzantiumClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Byzantium_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ByzantiumServer is the server API for Byzantium service.
// All implementations must embed UnimplementedByzantiumServer
// for forward compatibility.
type ByzantiumServer interface {
	GetMessage(context.Context, *Empty) (*Message, error)
	SendMessage(context.Context, *Message) (*Empty, error)
	mustEmbedUnimplementedByzantiumServer()
}

// UnimplementedByzantiumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByzantiumServer struct{}

func (UnimplementedByzantiumServer) GetMessage(context.Context, *Empty) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedByzantiumServer) SendMessage(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedByzantiumServer) mustEmbedUnimplementedByzantiumServer() {}
func (UnimplementedByzantiumServer) testEmbeddedByValue()                   {}

// UnsafeByzantiumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ByzantiumServer will
// result in compilation errors.
type UnsafeByzantiumServer interface {
	mustEmbedUnimplementedByzantiumServer()
}

func RegisterByzantiumServer(s grpc.ServiceRegistrar, srv ByzantiumServer) {
	// If the following call pancis, it indicates UnimplementedByzantiumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Byzantium_ServiceDesc, srv)
}

func _Byzantium_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByzantiumServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byzantium_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByzantiumServer).GetMessage(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byzantium_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByzantiumServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byzantium_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByzantiumServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Byzantium_ServiceDesc is the grpc.ServiceDesc for Byzantium service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Byzantium_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Byzantium",
	HandlerType: (*ByzantiumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _Byzantium_GetMessage_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Byzantium_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc.proto",
}
